ContasaApplication/Controllers/DespesasController.cs
using System.Globalization;
using ContasApplication.Models;
using ContasApplication.Repository;
using Microsoft.AspNetCore.Mvc;

namespace ContasApplication.Controllers
{
    public class DespesasController : Controller
    {
        private readonly IDespesaRepository _despesaRepository;
        public DespesasController(IDespesaRepository despesaRepository)
        {
            _despesaRepository = despesaRepository;
        }

        public IActionResult Index()
        {
            var despesas = new DespesaAuxiliar();
            var idUsuario = HttpContext.Session.GetInt32("UsuarioId") ?? 0;

            despesas.ListDespesas = _despesaRepository.FindDespesaMes(DateTime.Now, idUsuario);
            despesas.ValorTotal = _despesaRepository.GetValorTotalDespesa(despesas.ListDespesas);
            despesas.Etiquetas = _despesaRepository.FindAllEtiquetas();

            return View(despesas);
        }

        public IActionResult AddDespesa()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddDespesa(DespesaModel despesa)
        {
            despesa.UsuarioId = HttpContext.Session.GetInt32("UsuarioId") ?? 0;
            despesa.ValorDespesa = Convert.ToDouble(despesa.ValorDespesa.ToString().Replace(",", "."), CultureInfo.InvariantCulture);

            if (despesa.NomeDespesa != "")
            {
                _despesaRepository.AddDespesa(despesa);
                return RedirectToAction("Index");
            }

            return View(despesa);
        }

        public IActionResult RemoveDespesaView()
        {
            int idUsuario = HttpContext.Session.GetInt32("UsuarioId")?? 0;
            var despesas = new DespesaAuxiliar();

            despesas.ListDespesas = _despesaRepository.FindDespesaMes(DateTime.Now, idUsuario);
            despesas.ValorTotal = _despesaRepository.GetValorTotalDespesa(despesas.ListDespesas);

            return View(despesas);
        }

        public IActionResult RemoveDespesa(int id)
        {
            int idUsuario = HttpContext.Session.GetInt32("UsuarioId") ?? 0;

            var despesa = _despesaRepository.FindDespesaById(id, idUsuario);

            if (despesa.Parcelado == true)
            {
                return RedirectToAction("RemoveParceladoConfirm", despesa);
            }

            _despesaRepository.RemoveDespesa(id, idUsuario);
            return RedirectToAction("Index");
        }

        public IActionResult RemoveParceladoConfirm(DespesaModel despesa)
        {
            return View(despesa);
        }

        public IActionResult RemoveParceladoConfirmMes(int id)
        {
            int idUsuario = HttpContext.Session.GetInt32("UsuarioId") ?? 0;

            _despesaRepository.RemoveDespesa(id, idUsuario);
            return RedirectToAction("Index");
        }

        public IActionResult RemoveParceladoConfirmTodos(int id)
        {
            int idUsuario = HttpContext.Session.GetInt32("UsuarioId") ?? 0;

            _despesaRepository.RemoveDespesa(id, idUsuario);
            return RedirectToAction("Index");
        }
    }
}

ContasaApplication/Views/Despesas/AddDespesa.cshtml
@using ContasApplication.Enums
@using ContasApplication.Models
@model DespesaModel;
@{
	ViewData["Title"] = "Adicionar despesa";
}
<div class="background"><</div>
<div class="container">
	<div>
		<form asp-controller="Despesas" asp-action="AddDespesa" method="post" id="formAddDespesa">

			<div class="form-group">
				<label id="labelInputConfig" for="Name">Nome</label>
				<input asp-for="NomeDespesa" type="text" class="form-control" placeholder="Dê um nome da despesa" maxlength="35">
				@Html.ValidationMessageFor(x => x.NomeDespesa)
			</div>

			<div class="form-group">
				<label id="labelInputConfig" for="Price">Valor</label>
				<input asp-for="ValorDespesa" type="text" class="form-control" id="Price" placeholder="Digite o valor da despesa" min="0" maxlength="12">
			</div>

			<div class="form-group">
				<label id="labelInputConfig" for="Etiquetas">Etiquetas</label>
				<select asp-for="Etiqueta" class="form-control" id="Etiquetas">
					<option value="0">Selecione uma etiqueta</option>
					<option value="1">"&#x1F3E0 - Moradia</option>
					<option value="2">"&#x1F697 - Transporte</option>
					<option value="3">"&#x1F37D - Alimentação</option>
					<option value="4">"&#x1F691 - Saúde</option>
					<option value="5">"&#x1F4D6 - Educação</option>
					<option value="6">"&#x1F37F - Lazer</option>
					<option value="7">"&#x1F4B8 - Dívidas</option>
					<option value="8">"&#x1F416 - Imprevistos</option>
					</select>
			</div>

			<div class="form-check">
				<input class="form-check-input" type="checkbox" asp-for="Parcelado" id="flexCheckDefault">
				<label id="labelInputConfig" class="form-check-label" for="Parcelado">
					Essa despesa é parcelada?
				</label>
			</div>

			<div id="parcelado" style="display: none">
				<label id="labelInputConfig" for="Parcelas">Quantidade de parcelas</label>
				<input id="QuantidadeParcelas" asp-for="QuantidadeParcelas" type="number" class="form-control" placeholder="0" min="0" max="500">

				<label id="labelInputConfig" for="Parcelas">Quantidade de parcelas</label>
				<input id="QuantidadeParcelasPagas" asp-for="QuantidadeParcelasPagas" type="number" class="form-control" placeholder="0" min="0" max="500">
			</div>

			<div class="form-check-despesaFutura">
				<input class="form-check-input" type="checkbox" asp-for="Parcelado" id="flexCheckDefault">
				<label id="labelInputConfig" class="form-check-label" for="Parcelado">
					Essa é uma despesa com data futura?
				</label>
			</div>

			<div style=" display: none" id="dataFutura">
				<label id="labelInputConfig" for="parcelaFutura">Data futura</label>
				<input asp-for="CreateDate" type="date" class="form-control" placeholder="dd/mm/aaaa">
			</div>

			<div>
				<input class="form-check-input" type="checkbox" asp-for="DespesaFixa" id="flexCheckDefault2">
				<label id="labelInputConfig" class="form-check-label" for="Parcelado">Essa é uma conta fixa?</label>
			</div>

			<button type="submit" class="btn btn-primary">Adicionar</button>
			<a role="button" class="btn btn-secondary" asp-controller="Despesas" asp-action="Index">Voltar</a>
		</form>
	</div>

</div>





<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/js/AddDespesa.js"></script>

<script src="https://cdn.jsdelivr.net/npm/cleave.js/dist/cleave.min.js"></script>
<link rel="stylesheet" type="text/css" href="~/css/AddDespesaView.css" />

ContasaApplication/Views/Despesas/Index.cshtml
@using ContasApplication.Models
@using System.Globalization
@model DespesaAuxiliar;
@{
	ViewData["Title"] = "Index Page";
}

<div class="text-center" id="containerIndex">
	<a role="button" class="btn btn-primary" asp-controller="Despesas" asp-action="AddDespesa">Nova despesa</a>
	<a role="button" class="btn btn-danger" asp-controller="Despesas" asp-action="RemoveDespesaView">Remover despesa</a>

	<table class="table table-striped" id="table-Despesas">
		<thead>
			<tr>
				<th scope="col">Nome</th>
				<th scope="col">Valor</th>
				<th scope="col" class="hidden-on-small">Data</th>
				<th scope="col" class="hidden-on-small">Num.Parcelas</th>
				<th scope="col" class="hidden-on-small">Paga(s)</th>
				<th scope="col">Tipo</th>
			</tr>
		</thead>
		<tbody>
			@if (Model.ListDespesas != null && Model.ListDespesas.Any())
			{
				@foreach (DespesaModel item in Model.ListDespesas)
				{
					<tr>
						<td>@item.NomeDespesa</td>
						<td>@item.ValorDespesa.ToString("C", new System.Globalization.CultureInfo("pt-BR"))</td>
						<td class="hidden-on-small">@item.CreateDate</td>
						<td class="hidden-on-small">@item.QuantidadeParcelas</td>
						<td class="hidden-on-small" >@item.QuantidadeParcelasPagas</td>
						@if (item.Etiqueta != 0)
						{
							foreach (var item2 in Model.Etiquetas)
							{
								if (item.Etiqueta == item2.EtiquetaId)
								{
									<td>@Html.Raw(@item2.Icone) - @item2.Nome</td>
								}
							}
						}
					</tr>
				}
			}
			<tr>
				<td>
					@Model.ValorTotal.ToString("C", new System.Globalization.CultureInfo("pt-BR"))
				</td>
			</tr>
		</tbody>
	</table>


@* 	<div id="grafico">
		<canvas id="grafico1"></canvas>
	</div>

	<script>
		const ctx = document.getElementById('grafico1');

		new Chart(ctx, {
		  type: 'bar',
		  data: {
			labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
			datasets: [{
			  label: '# of Votes',
			  data: [12, 19, 3, 5, 2, 3],
			  borderWidth: 1
			}]
		  },
		  options: {
			scales: {
			  y: {
				beginAtZero: true
			  }
			}
		  }
		});
	</script> *@

</div>

<link rel="stylesheet" type="text/css" href="~/css/IndexDespesa.css" />

ContasaApplication/Views/Despesas/ProjecaoDespesa.cshtml
@{
	ViewData["Title"] = "Projeção de Despesas";
}

<div class="container">
	<div class="item"></div>
	<div class="item"></div>
	<div class="item"></div>
</div>

<link rel="stylesheet" type="text/css" href="~/css/ProjecaoDespesa.css" />

ContasaApplication/Views/Despesas/RemoveDespesaView.cshtml
@using ContasApplication.Models;
@model DespesaAuxiliar;
@{
	ViewData["Title"] = "Remove Despesa";
}

<div class="text-center">
	<table class="table table-striped" id="table-Despesas">
		<thead>
			<tr>
				<th scope="col">Nome</th>
				<th scope="col">Valor</th>
			</tr>
		</thead>
		<tbody>
			@if (Model.ListDespesas != null && Model.ListDespesas.Any())
			{
				@foreach (DespesaModel item in Model.ListDespesas)
				{
					<tr>
						<td>@item.NomeDespesa</td>
						<td>@item.ValorDespesa</td>
						<td>
							<a role="button" class="btn btn-danger"
							   asp-controller="Despesas" asp-action="RemoveDespesa" asp-route-id="@item.Id">Apagar</a>
						</td>
					</tr>
				}
			}
		</tbody>
	</table>
	<div class="text-start">
		<a role="button" class="btn btn-secondary" asp-controller="Despesas" asp-action="Index">Voltar</a>
	</div>
</div>

ContasaApplication/Views/Despesas/RemoveParceladoConfirm.cshtml
@using ContasApplication.Models;
@model DespesaModel;

@{
	ViewData["Title"] = "Remove Despesa Parcelada";
}

<h1>
	REMOVER DESPESA PARCELADA (@Model.NomeDespesa, de valor @Model.ValorDespesa)
	<a role="button" class="btn btn-danger"
	   asp-controller="Despesas" asp-action="RemoveParceladoConfirmMes" asp-route-id="@Model.Id" >Apagar somente a do mês</a>

	<a role="button" class="btn btn-danger"
	   asp-controller="Despesas" asp-action="RemoveParceladoConfirmTodos" asp-route-id="@Model.Id">Apagar tudo</a>
	<a role="button" class="btn btn-secondary" asp-controller="Despesas" asp-action="Index">Voltar</a>

</h1>