ContasaApplication/Controllers/LoginController.cs
using ContasApplication.Models;
using ContasApplication.Repository;
using Microsoft.AspNetCore.Mvc;

namespace ContasApplication.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;
        public LoginController(IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RotaLoginRegistro(Usuarios usuarios)
        {
            bool verificacao = false;
            if (usuarios.Page == Enums.PageEnum.Login)
            {
                if (string.IsNullOrEmpty(usuarios.Usuario))
                {
                    TempData["MostrarModal"] = "True";
                    TempData["MensagemErro"] = "É obrigatório informar o usuário.";
                    return View("Index");
                }
                if (string.IsNullOrEmpty(usuarios.Senha))
                {
                    TempData["MostrarModal"] = "True";
                    TempData["MensagemErro"] = "A senha é obrigatória!";
                    return View("Index");
                }

                verificacao = _usuarioRepository.LoginUsuario(usuarios);
                if (verificacao == false)
                {
                    TempData["MostrarModal"] = "True";
                    TempData["MensagemErro"] = "Usuário ou senha inválidos.";
                    return View("Index");
                }
            }
            else
            {
                var validacaoRegistroUsuarioNome = _usuarioRepository.ValidarLoginUsuario(usuarios.Usuario);
                var validacaoRegistroUsuarioEmail = false;
                if (usuarios.Email != null)
                {
                    validacaoRegistroUsuarioEmail = _usuarioRepository.ValidarLoginUsuario(usuarios.Email);
                }
                if (string.IsNullOrEmpty(usuarios.Usuario))
                {
                    TempData["MostrarModal"] = "True";
                    TempData["MensagemErro"] = "É obrigatório informar o usuário.";
                    return View("Index");
                }
                if (validacaoRegistroUsuarioNome == true)
                {
                    TempData["MostrarModal"] = "True";
                    TempData["MensagemErro"] = "Já existe um usuário com este nome.";
                    return View("Index");
                }
                if (validacaoRegistroUsuarioEmail == true)
                {
                    TempData["MostrarModal"] = "True";
                    TempData["MensagemErro"] = "Já existe um usuário com este endereço de email.";
                    return View("Index");
                }
                if (string.IsNullOrEmpty(usuarios.Email))
                {
                    TempData["MostrarModal"] = "True";
                    TempData["MensagemErro"] = "Informe um email válido.";
                    return View("Index");
                }
                if (string.IsNullOrEmpty(usuarios.Senha))
                {
                    TempData["MostrarModal"] = "True";
                    TempData["MensagemErro"] = "A senha é obrigatória!";
                    return View("Index");   
                }
                _usuarioRepository.RegistrarUsuario(usuarios);
            }

            if (verificacao == false)
            {
                return RedirectToAction("Index");
            }
            var idUsuario = _usuarioRepository.GetIdUsuarioPeloLogin(usuarios.Usuario);
            HttpContext.Session.SetInt32("UsuarioId", idUsuario);
            return RedirectToAction("Index", "Despesas");
        }
    }
}

ContasaApplication/Controllers/ProjecaoController.cs
using ContasApplication.Models;
using ContasApplication.Repository;
using Microsoft.AspNetCore.Mvc;

namespace ContasApplication.Controllers
{
    public class ProjecaoController : Controller
    {
        private readonly IDespesaRepository _despesaRepository;
        public ProjecaoController(IDespesaRepository despesaRepository)
        {
            _despesaRepository = despesaRepository;
        }

        public IActionResult Index()
        {
            int idUsuario = HttpContext.Session.GetInt32("UsuarioId") ?? 0;

            var despesaAuxiliarLista = new List<DespesaAuxiliar>();
            var mesesComDespesa = _despesaRepository.FindAllMesDespesas();
            var despesas = _despesaRepository.FindAllDespesa(idUsuario);

            foreach (var mes in mesesComDespesa)
            {
                var despesaAuxiliar = new DespesaAuxiliar();
                despesaAuxiliar.Mes = mes;
                despesaAuxiliar.ListDespesas = new List<DespesaModel>();
                despesaAuxiliar.Etiquetas = _despesaRepository.FindAllEtiquetas();

                foreach (var despesa in despesas)
                {
                    if (despesa.CreateDate.Month == mes.MesReferenciaId.Month || despesa.DespesaFixa == true)
                    {
                        despesaAuxiliar.ListDespesas.Add(despesa);
                        despesaAuxiliar.ValorTotal += despesa.ValorDespesa;
                    }
                }

                despesaAuxiliarLista.Add(despesaAuxiliar);
            }

            return View(despesaAuxiliarLista);
        }
    }
}

ContasaApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContasApplication</title>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ContasaApplication.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>

    <nav class="menu-lateral">
        <div class="btn-expandir">
            <i class="bi bi-list"></i>

            <ul class="navbar-nav flex-grow-1">
                <li class="item-menu">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Despesas" asp-action="Index">
                        <span class="icon"><i class="bi bi-house"></i></span>
                        <span class="txt-link">Início</span>
                    </a>
                </li>
                <li class="item-menu">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Projecao" asp-action="Index">
                        <span class="icon"><i class="bi bi-calendar-date"></i></span>
                        <span class="txt-link">Projeção</span>
                    </a>
                </li>
            </ul>

        </div>
    </nav>

    <header class="header-principal" >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Despesas" asp-action="Index">ContasApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Despesas" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projecao" asp-action="Index">Projeção</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Sair</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> 
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div>
            &copy; 2025 - ContasApplication - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>